[workspace]
resolver = "2"
members = [
  "session-policy",
  "referral",
]

[workspace.dependencies.soroban-sdk]
version = "25.3.1"

[workspace.dependencies.stellar-accounts]
git = "https://github.com/OpenZeppelin/stellar-contracts"
tag = "v0.7.0"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
